"""Identity Evolution Proposal schema — generated by AIA; persisted/served by Backend."""

from __future__ import annotations

from datetime import datetime
from typing import List, Literal, Optional

from pydantic import BaseModel, Field

ProposedChangeAction = Literal["add", "remove", "reweight"]


class ProposedChange(BaseModel):
    action: ProposedChangeAction
    attributeId: str
    attributeLabel: str
    newWeight: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    reason: str
    evidenceIds: List[str] = Field(default_factory=list, description="Cites supporting evidence IDs (>= 3 required)")


class IdentityEvolutionProposal(BaseModel):
    proposalId: str
    userId: str
    declaredSelfVersion: int
    proposedChanges: List[ProposedChange]
    supportingEvidenceIds: List[str] = Field(default_factory=list)
    narrative: str
    generatedAt: datetime
