"""Weekly Becoming Report schema — generated by AIA; persisted/served by Backend."""

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class WeeklyReport(BaseModel):
    id: str = Field(description="Unique report ID")
    userId: str
    gapScoreStart: Optional[int] = Field(default=None, description="Gap score at start of window")
    gapScoreEnd: int = Field(description="Gap score at end of window")
    gapDelta: int = Field(description="gapScoreEnd - gapScoreStart (negative = improvement)")
    narrative: str = Field(description="Identity movement narrative focusing on identity evolution, not time-tracking")
    highlights: List[str] = Field(default_factory=list, description="2-4 key identity progress bullets")
    generatedAt: datetime
    simulated: bool = Field(default=True, description="PRD §9 honesty label constraint")
